#!/bin/bash

set -xe

RUN_DIR=/var/vcap/sys/run/start_flaqs
LOG_DIR=/var/vcap/sys/log/start_flaqs

PIDFILE=$RUN_DIR/flaqs.pid
RUNAS=vcap

export PYTHONPATH=/var/vcap/packages/flaqs/lib/lib/python2.7/site-packages:

# export PATH=/var/vcap/packages/ruby/bin:$PATH
# export BUNDLE_GEMFILE=/var/vcap/packages/simple_server/Gemfile
# export GEM_HOME=/var/vcap/packages/simple_server/gem_home/ruby/2.1.0

function pid_exists() {
  ps -p $1 &> /dev/null
}

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    export CONFIG_FILE=/var/vcap/jobs/start_flaqs/config/config.json

    exec chpst -u $RUNAS:$RUNAS \
	python /var/vcap/packages/flaqs/flaqs.py
      >>$LOG_DIR/server.stdout.log 2>>$LOG_DIR/server.stderr.log
    ;;
  stop)
    PID=$(head -1 $PIDFILE)
    if [ ! -z $PID ] && pid_exists $PID; then
      kill $PID
    fi
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: ctl {start|stop|console}" ;;
esac
exit 0
