---
name: start-flaqs
director_uuid: 24747b4d-410a-46ef-8218-858d818cd04e

releases:
- name: start_flaqs
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.0.0/28
    reserved: [10.244.0.1]
    static: [10.244.0.2, 10.244.0.6, 10.244.0.10]
    cloud_properties:
      name: random

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 1
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: flaqs
  templates:
  - name: start_flaqs
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.0.2
  properties: {}

